[build]
       base    = "wildstone-frontend"
       command = "npm run build"
       publish = "build"

[[redirects]]
  from = "http://wildstonesolutions.com/*"
  to = "https://www.wildstonesolutions.com/:splat"
  status = 301
  force = true